dataset_name: finer
original_dataset: configs/datasets/finer/data/finer.conll

# config for knowledge augmented
data_dir_ka: configs/datasets/finer/data_ka   # where train.jsonl/val.jsonl/test.jsonl exist
dataset_to_evaluate_ka: 
  - test # folder of the jsonl data to evaluate
dataset_to_predict_ka: 
  - test # folder of the jsonl data to predict
output_dir_ka: configs/datasets/finer/output_ka # where the trained/finetuned models or predictions are saved

# config for traditional
data_dir_trad: configs/datasets/finer/data_trad   # where train.jsonl/val.jsonl/test.jsonl exist
dataset_to_evaluate_trad: 
  - test # folder of the jsonl data to evaluate
dataset_to_predict_trad: 
  - test # folder of the jsonl data to predict
output_dir_trad: configs/datasets/finer/output_trad # where the trained/finetuned models or predictions are saved
labels_trad: configs/datasets/finer/data_trad # a folder to jsonl data files where the possible output labels may be picked

do_train: true
do_eval: true
evaluate_during_training: true
overwrite_output_dir: true
per_gpu_train_batch_size: 128
per_gpu_eval_batch_size: 128
num_train_epochs: 10

entity_groups:
  - name: QUANTITY
    tags: [QUANTITY]
    type: quantity
    group: measurements
    group_definition: "Quantity specify the amount of an ingredient."
    definition: "Quantity specify the amount of an ingredient."
    examples: ["1", "1 3/4", "4.25", "1/8", "25"]
    question: "What is the quantity mentioned in the text?"

  - name: UNIT
    tags: [UNIT]
    type: unit
    group: measurements
    group_definition: "Unit describe the measurement system or scale of the quantity."
    definition: "Unit describe the measurement system or scale of the quantity."
    examples: ["pieces", "cup", "fluid ounce", "fluid ounces", "tablespoons"]
    question: "What is the unit mentioned in the text?"

  - name: ING
    tags: [ING]
    type: ingredient
    group: ingredients
    group_definition: "Ingredients are the primary food components used in recipes."
    definition: "Ingredients are the primary food components used in recipes."
    examples: ["butter", "vegetable oil", "red bell pepper", "honey maid graham crumbs"]
    question: "What is the ingredient mentioned in the text?"

  - name: PRODUCT
    tags: [PRODUCT]
    type: products
    group: products
    group_definition: "Products are food or ingredient from specific brand mentioned."
    definition: "Products are food or ingredient from specific brand mentioned."
    examples: ["tabasco", "Tabasco brand chipotle pepper sauce", "archer frozen cut green beans"]
    question: "What is the product mentioned in the text?"

  - name: STATE
    tags: [STATE]
    type: state
    group: state
    group_definition: "State is the processing state of the food or ingredient."
    definition: "State is the processing state of the food or ingredient"
    examples: ["medium", "peeled and cut into 0.25 inch cubes", "cut in half"]
    question: "What is the state mentioned in the text?"

split_ratios:
  train: 0.8
  val: 0.1
  test: 0.1
