dataset_name: tasteset1
original_dataset: configs/datasets/tasteset1/data/TASTEset.csv

# config for knowledge augmented
data_dir_ka: configs/datasets/tasteset1/data_ka   # where train.jsonl/val.jsonl/test.jsonl exist
dataset_to_evaluate_ka: 
  - test # folder of the jsonl data to evaluate
dataset_to_predict_ka: 
  - test # folder of the jsonl data to predict
output_dir_ka: configs/datasets/tasteset1/output_ka # where the trained/finetuned models or predictions are saved

# config for traditional
data_dir_trad: configs/datasets/tasteset1/data_trad   # where train.jsonl/val.jsonl/test.jsonl exist
dataset_to_evaluate_trad: 
  - test # folder of the jsonl data to evaluate
dataset_to_predict_trad: 
  - test # folder of the jsonl data to predict
output_dir_trad: configs/datasets/tasteset1/output_trad # where the trained/finetuned models or predictions are saved
labels_trad: configs/datasets/tasteset1/data_trad # a folder to jsonl data files where the possible output labels may be picked

do_train: true
do_eval: true
evaluate_during_training: true
overwrite_output_dir: true
per_gpu_train_batch_size: 128
per_gpu_eval_batch_size: 128
num_train_epochs: 30

entity_groups:
  - name: QUANTITY
    tags: [QUANTITY]
    type: quantity
    group: quantity
    group_definition: "Quantity specify the amount of an ingredient."
    definition: "Quantity specify the amount of an ingredient."
    examples: ["1", "1 3/4", "4.25", "1/8", "25"]
    question: "What is the quantity mentioned in the text?"

  - name: UNIT
    tags: [UNIT]
    type: unit
    group: unit
    group_definition: "Unit describe the measurement system or scale of the quantity."
    definition: "Unit describe the measurement system or scale of the quantity."
    examples: ["pieces", "cup", "fluid ounce", "fluid ounces", "tablespoons"]
    question: "What is the unit mentioned in the text?"

  - name: FOOD
    tags: [FOOD]
    type: food
    group: food
    group_definition: "Ingredients are the primary food components used in recipes."
    definition: "Ingredients are the primary food components used in recipes."
    examples: ["butter", "vegetable oil", "red bell pepper", "honey maid graham crumbs"]
    question: "What is the ingredient mentioned in the text?"

  - name: PROCESS
    tags: [PROCESS]
    type: process
    group: process
    group_definition: "Process is an attribute of the ingredient that usually refer to an action to be taken to prepare the ingredient."
    definition: "Process is an attribute of the ingredient that usually refer to an action to be taken to prepare the ingredient."
    examples: ["refrigerated", "melted", "crushed", "grated"]
    question: "What is the process mentioned in the text?"

  - name: PHYSICAL_QUALITY
    tags: [PHYSICAL_QUALITY]
    type: physical_quality
    group: physical_quality
    group_definition: "Physical quality is the physical characteristic of the ingredient."
    definition: "Physical quality is the physical characteristic of the ingredient."
    examples: ["boneless", "frozen", "fresh", "dried", "powdered"]
    question: "What is the physical quality mentioned in the text?"

  - name: COLOR
    tags: [COLOR]
    type: color
    group: color
    group_definition: "Color denotes the visual appearance or hue of the ingredient."
    definition: "Color denotes the visual appearance or hue of the ingredient."
    examples: ["brown", "green", "white"]
    question: "What is the color mentioned in the text?"

  - name: TASTE
    tags: [TASTE]
    type: taste
    group: taste
    group_definition: "Taste is the flavor of the ingredient."
    definition: "Taste is the flavor of the ingredient."
    examples: ["bittersweet", "butter-flavoured", "sweet", "semi-sweet"]
    question: "What is the taste mentioned in the text?"

  - name: PURPOSE
    tags: [PURPOSE]
    type: purpose
    group: purpose
    group_definition: "Purpose is the reason of using the ingredient in the recipe."
    definition: "Purpose is the reason of using the ingredient in the recipe."
    examples: ["for dusting", "for garnish", "for frying", "as topping"]
    question: "What is the purpose mentioned in the text?"

  - name: PART
    tags: [PART]
    type: part
    group: part
    group_definition: "Part refers to a specific portion of an ingredient needed for a recipe."
    definition: "Part refers to a specific portion of an ingredient needed for a recipe."
    examples: ["breast halves", "yolks", "breasts", "tablespoons"]
    question: "What is the part mentioned in the text?"

split_ratios:
  train: 0.74
  val: 0.1
  test: 0.16
